<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitca282b93a3de6ca2fac79d15bcb35b8e
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'APP\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'APP\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitca282b93a3de6ca2fac79d15bcb35b8e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitca282b93a3de6ca2fac79d15bcb35b8e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitca282b93a3de6ca2fac79d15bcb35b8e::$classMap;

        }, null, ClassLoader::class);
    }
}
